### ISSUE TITLE
problem z logowaniem

### ISSUE THREAD

**Issue by szwagierluki** [Grycek/ChomikDownloader#5]
Traceback (most recent call last):
  File "./chomik_downloader", line 7, in <module>
    chomikdownloader.main.start()
  File "/usr/local/lib/python2.7/dist-packages/chomikdownloader/main.py", line 52, in start
    d = downloader.Downloader(login, password,  debug = debug, threads = threads)
  File "/usr/local/lib/python2.7/dist-packages/chomikdownloader/downloader.py", line 96, in __init__
    if not self.chomik.login(self.user, self.password):
  File "/usr/local/lib/python2.7/dist-packages/chomikdownloader/chomikbox.py", line 161, in login
    if self.relogin() == True:
  File "/usr/local/lib/python2.7/dist-packages/chomikdownloader/chomikbox.py", line 202, in relogin
    self.log_www()
  File "/usr/local/lib/python2.7/dist-packages/chomikdownloader/chomikbox.py", line 225, in log_www
    resp = opener.open("http://chomikuj.pl/action/chomikbox/DownloadFolderChomikBox", data)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error

Jak naprawić ?

**Comment by Grycek** [comment]
Czy błąd dalej występuje? Nie miałem ostatnio za bardzo czasu tym się zająć. Spojrzę na to w najbliższym czasie.

**Comment by arcaine2** [comment]
Niestety wciaz tak:

```
Logowanie
Traceback (most recent call last):
  File "chomik_downloader", line 11, in <module>
    src.main.start()
  File "/home/arcain/Projects/ChomikDownloader/src/main.py", line 52, in start
    d = downloader.Downloader(login, password,  debug = debug, threads = threads)
  File "/home/arcain/Projects/ChomikDownloader/src/downloader.py", line 96, in __init__
    if not self.chomik.login(self.user, self.password):
  File "/home/arcain/Projects/ChomikDownloader/src/chomikbox.py", line 161, in login
    if self.relogin() == True:
  File "/home/arcain/Projects/ChomikDownloader/src/chomikbox.py", line 202, in relogin
    self.log_www()
  File "/home/arcain/Projects/ChomikDownloader/src/chomikbox.py", line 225, in log_www
    resp = opener.open("http://chomikuj.pl/action/chomikbox/DownloadFolderChomikBox", data)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error

```

**Comment by Grycek** [comment]
Wprowadziłem drobne zmiany. Może teraz będzie lepiej działało.

**Comment by arcaine2** [comment]
Teraz u mnie dziala w porzadku co jest ogolnie swietnia wiadomoscia bo to chyba jedyny sposob na rekursywne pobranie calych katalogow z wlasnego chomika. Dzieki.

**Comment by szwagierluki** [comment]
...a mi dalej nie działa

Traceback (most recent call last):
  File "./chomik_downloader", line 7, in <module>
    chomikdownloader.main.start()
  File "/usr/local/lib/python2.7/dist-packages/chomikdownloader/main.py", line 52, in start
    d = downloader.Downloader(login, password,  debug = debug, threads = threads)
  File "/usr/local/lib/python2.7/dist-packages/chomikdownloader/downloader.py", line 96, in __init__
    if not self.chomik.login(self.user, self.password):
  File "/usr/local/lib/python2.7/dist-packages/chomikdownloader/chomikbox.py", line 167, in login
    if self.relogin() == True:
  File "/usr/local/lib/python2.7/dist-packages/chomikdownloader/chomikbox.py", line 212, in relogin
    self.log_www()
  File "/usr/local/lib/python2.7/dist-packages/chomikdownloader/chomikbox.py", line 239, in log_www
    self.chomikbox_url = re.findall("""chomik://files/:(\d*)/""", cont)[0]
IndexError: list index out of range

**Comment by arcaine2** [comment]
To to akurat kolejny problem, ktory tez mi sie pojawil po pobraniu calej sterty rzeczy. Zgloszony w kolejnym "issue".

**Comment by Grycek** [comment]
Wprowadziłem kolejne poprawki.

**Comment by szwagierluki** [comment]
mhm dla mnie działa :))))
dzięki...

**Comment by arcaine2** [comment]
Jest lepiej, tamtego bledu juz nie ma, program wznowil pobieranie ale u mnie po czasie pojawia sie cos takiego i to dla kazdego kolejnego pobieranego pliku:

`Blad: ('http error', 401, 'Unauthorized', <httplib.HTTPMessage instance at 0x7fa9efb93d40>)`

PS. Gdyby udalo ci sie poprawic jeszcze Uploadera, tak zeby pomijal juz istniejace pliki, o ile w ogole taka mozliwosc istnieje, to bylo by swietnie.
